version: "3.9"

services:

  app:
    container_name: app_trade
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_db_is_up &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: app_db
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  pgAdmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      depends_on:
        - db
      ports:
        - 8080:80
      environment:
        - PGADMIN_DEFAULT_EMAIL=devuser@email.com
        - PGADMIN_DEFAULT_PASSWORD=changeme
      volumes:
        - ./pgadmin:/var/lib/pgadmin
        - ./pgadmin:/certs/server.cert
        - ./pgadmin:/certs/server.key
        - ./pgadmin:/pgadmin4/servers.json


volumes:
  dev-db-data:
  dev-static-data: