# Generated by Django 4.0.10 on 2024-03-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
