# Generated by Django 4.0.10 on 2024-03-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0007_user_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.ManyToManyField(blank=True, null=True, to='payments.paymentmethod'),
        ),
    ]
