# Generated by Django 4.0.10 on 2024-03-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0008_remove_user_payment_method_user_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='payments.paymentmethod'),
        ),
    ]
