# Generated by Django 4.0.10 on 2024-03-15 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_rename_payment_method_id_paymentmethoduser_payment_method_name_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_type', models.CharField(choices=[('buy', 1), ('sell', 2)], default=('buy', 1), max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethoduser')),
            ],
        ),
    ]
