# Generated by Django 4.0.10 on 2024-03-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default=('buy', 'buy'), max_length=100),
        ),
    ]
