# Generated by Django 4.0.10 on 2024-03-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offers.offerstatus'),
        ),
    ]
