# Generated by Django 4.0.10 on 2024-03-14 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method_id', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ManyToManyField(to='payments.paymentmethod')),
            ],
        ),
    ]
