# Generated by Django 4.0.10 on 2024-03-14 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_paymentmethoduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethoduser',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
