# Generated by Django 4.0.10 on 2024-03-14 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_paymentmethoduser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethoduser',
            old_name='payment_method_id',
            new_name='payment_method_name_id',
        ),
        migrations.RemoveField(
            model_name='paymentmethoduser',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='paymentmethoduser',
            name='payment_method',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='paymentmethoduser',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentmethoduser',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
